# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "YLTYusBdmlFNQCz7yJdf5QKRqllp42lfAafCgJOBEsqfEwRgXV/tJYMjkvSk5fELz2a9pjZbKpuhQtfdP7y2jKZ9aImzJSoyD1yP9ppkGp82nbr+hAABjf41mhb/GB/8EizyEH2BFvn6yJ2MlcVCElemDqx9iBd8EiKbVNCEdOFdDojmGYHdlAQXE3l3hdkz+5tuijbZyUezQzyp3wiH8tGWpXZvNB4T+Sx/XackJ9hsJ7CaLkwZrDA6ybaZZ1pcjYvmoesw0YX4TU6vSJUREsyaV6QRy+89lNnwbQ/Z8f77pdSrOs4/rdMNyKoXQ0Z8xpLTCXg4lRhZPKjAbBkWqlAOXD7aVEf2BXnJQw1kFe/iNH/laJXcg5ggMDOPJD/Y9r4j/5cWdPoMAFNT4AHh0pUq3r/ve18wTE8S/XVxHFLMZ0QwDGCncnneoYrc1P6QvTPVKxCuQJUqIT43/zfi9/IOSkyH9jIU8iAd2D7eFxFa75iB4t6OGTuFfwJcmJYX+rutUmuJ8gxaqVOp1kmkfwUv6UDQwgY49UN0c4+Dmw6oqqyLfP76lafwA+HneyaVb/ua7szF3qWYyEbHbpLU7kwVyfomFHYLgFME+TXgWdxxPMNhGMOVfSqIpECFCJsydyHtlRLN6SHx8z2AAy+YkGJ/7y9nwt8rTPD4CkOnEjI="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - tree
  coverity_scan:
    project:
      name: "troglobit/sntpd"
      description: "sntpd is a fork of ntpclient by Larry Doolittle"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure --prefix="
    build_command: "make clean all"
    branch_pattern: dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
script:
  - ./autogen.sh
  - ./configure --prefix=
  - make clean
  - make V=1 -j5
  - DESTDIR=/tmp make install-strip
  - tree /tmp
  - ldd  /tmp/bin/adjtimex /tmp/sbin/ntpclient
  - size /tmp/bin/adjtimex /tmp/sbin/ntpclient
  - /tmp/bin/adjtimex -h
  - /tmp/sbin/ntpclient -h
  - /tmp/sbin/sntpd -h
  - /tmp/sbin/ntpclient -c 1 -h pool.ntp.org
